export const projectsData = [
  {
    title: 'DjangoGameHub',
    description: 'A web platform hosting classic games like Snake, Flappy Bird, Tic-Tac-Toe, and Chrome\'s Dinosaur Game. Powered by Django and PostgreSQL for seamless performance, with HTML, CSS, and JavaScript for a captivating frontend. Track your scores, compete on the leaderboard, and aim for the top spot. Join the gaming community, challenge yourself, and let the games begin!',
    media: 'static/video/Django_game_hub.webm',
    poster: 'static/img/django_game_hub.png',
    link: 'https://github.com/Ghosts6/DjangoGameHub',
  },
  {
    title: 'TicketSystem',
    description: 'A ticket system built with Django, DRF, ORM, and frontend technologies like HTML, CSS, and JavaScript. The system allows clients to create ticket requests for the IT team, who can receive and respond to them efficiently.',
    media: 'static/video/ticket_system:.webm',
    poster: 'static/img/local_website.png',
    link: 'https://github.com/Ghosts6/Local-website',
  },
  {
    title: 'Matrix',
    description: 'In this section we can check my matrix project that I create matrix animations with language like c++,python,bash,cmd and html/css/js with different features',
    media: 'static/video/Matrix.webm',
    poster: 'static/img/matrix.png',
    link: 'https://github.com/Ghosts6/matrix',
  },
  {
    title: 'Hashing',
    description: 'A hash function is a mathematical algorithm that takes an input and produces output as a fixed-size string of characters, which is typically a hexadecimal or binary representation. Nowadays we have different hashing methods like md5, sha, sha-1, sha-256, bcrypt and if we want to rank them based on security: 🥇bcrypt 🥈sha-256 🥉ssha',
    media: 'static/img/salt-hash-password.jpg',
    link: 'https://github.com/Ghosts6/Hashing_methods',
  },
  {
    title: 'Optimize',
    description: 'Inside this repo I place two c++ code and python code to optimize linux and windows os, with help of this files you can optimize your system and make it faster just remind that for using this file you need admin access for windows you need run it as administrator and for linux you need password cuz command run on sudo and for compile codes you can use this commands \'gpp -o optimize optimize.cpp\' or \'g++ -o optimize optimize.cpp\' and then you can run it, i also create python code which do same thing for linux but with a bit extra feature',
    media: 'static/img/optimize.jpg',
    link: 'https://github.com/Ghosts6/optimize_os',
  },
  {
    title: 'WeatherNews',
    description: 'Here we have my weather project which created with help of django and include pages like home and weather, home page: inside this page you can check out weather news about cities around word, storm, torando, flood, weather in your place and etc also there are links so if something was interesting for you, you could read more about it. weather page: this page created for searching and check out weather in differend locations ,in this page by searching city name you will recive data about location like weather,temperature,wind speed,time and etc',
    media: 'static/video/weather_news.webm',
    poster: 'static/img/weather_news.png',
    link: 'https://github.com/Ghosts6/weather_news',
  },
  {
    title: 'V2ray & OpenVPN',
    description: 'This repo include bash files to setup and manage service like v2ray and openvpn in this repo we place two setup method and some scripts which you can use them for service management',
    media: 'static/img/openvpn.png',
    link: 'https://github.com/Ghosts6/v2ray_openvpn_setup',
  },
  {
    title: 'LibraryManagementSystem',
    description: 'This repository is dedicated to hosting programs written in languages such as C, C++, Bash, JavaScript, and Python, writed for library management systems. The projects within explore difference data modeling techniques, providing discussions on various methods employed for efficient data storage and retrieval.',
    media: 'static/video/Library_management_system.webm',
    poster: 'static/img/library_management.png',
    link: 'https://github.com/Ghosts6/Library_management_system',
  },
  {
    title: 'To-Do List',
    description: 'The To-Do List Application is a task management tool built with Django. It features a robust backend with REST API and ORM, and a user-friendly frontend using HTML, CSS, and JavaScript. Manage tasks, authenticate users, reset passwords, and access FAQs with ease.',
    media: 'static/img/Thumbnail .png',
    link: 'https://github.com/Ghosts6/To-Do-List',
  },
  {
    title: 'Blogging System',
    description: 'A Django and FastAPI-based platform for creating and managing articles with secure user authentication, a powerful API, and advanced filtering options.',
    media: 'static/img/Blogging.png',
    link: 'https://github.com/Ghosts6/Blogging-System',
  },
  {
    title: 'GhLight',
    description: 'I developed this website from the ground up, handling every aspect including backend, frontend, database management, and SEO. Utilizing Django for the backend and Django Rest Framework (DRF) for the API, I ensured robust functionality and performance. For testing, I implemented pytest and the pytest-django plugin. The database is managed with Django\'s ORM and SQLite. On the frontend, I employed HTML, JavaScript, CSS, and Bootstrap to create a modern and responsive interface. This website serves as an online store named "GhLight" showcasing and selling intelligent lighting products like moving head lights and other advanced lighting solutions. It includes various pages such as Home, Product Listings, Product Overview, Account Management, Checkout, About Us, FAQ, Contact Us, and Ticket Management. Users can explore products, view categories, watch introduction videos, and access services for inquiries, privacy policies, and terms of service.',
    media: 'static/img/ghlight.png',
    link: '#',
  },
];